handle SIGUSR1 nostop noprint pass
handle SIGUSR2 nostop noprint pass
handle SIG34 nostop noprint pass
handle SIG35 nostop noprint pass
handle SIG36 nostop noprint pass
handle SIG37 nostop noprint pass
handle SIG38 nostop noprint pass
handle SIG39 nostop noprint pass
handle SIG40 nostop noprint pass
handle SIG41 nostop noprint pass
handle SIG42 nostop noprint pass
handle SIG43 nostop noprint pass
handle SIG44 nostop noprint pass
handle SIG45 nostop noprint pass
handle SIG46 nostop noprint pass
handle SIG47 nostop noprint pass
handle SIG48 nostop noprint pass
handle SIG49 nostop noprint pass
handle SIG50 nostop noprint pass
handle SIG51 nostop noprint pass
handle SIG52 nostop noprint pass
handle SIG53 nostop noprint pass
handle SIG54 nostop noprint pass
handle SIG55 nostop noprint pass
handle SIG56 nostop noprint pass
handle SIG57 nostop noprint pass